component: cart
service_type: ClusterIP
port: 8080
PARAMETERS: "cart.prod.REDIS_HOST,REDIS_HOST cart.prod.CATALOGUE_HOST,CATALOGUE_HOST cart.prod.CATALOGUE_PORT,CATALOGUE_PORT"
schema:
  enabled: false

replicaCount: 2

resources:
  limits:
    cpu: 5000m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi