component: cart
service_type: ClusterIP
port: 8080
PARAMETERS: "cart.prod.REDIS_HOST,REDIS_HOST cart.prod.CATALOGUE_HOST,CATALOGUE_HOST cart.prod.CATALOGUE_PORT,CATALOGUE_PORT"
schema:
  enabled: false
